"use client";
import {createSpeechRecognition,speechErrorMessage} from "@/lib/speech-recognition";

import {useRef,useState} from "react";
import {useRouter} from "next/navigation";
import {alphabetLessons,alphabetOrder} from "@/lib/alphabet-data";
import "./alphabet.css";

const aliases:Record<string,string[]>={A:["a","ay","hey"],B:["b","bee","be"],C:["c","see","sea"],D:["d","dee"],E:["e","ee"],F:["f","eff"],G:["g","gee"],H:["h","aitch","haitch"],I:["i","eye"],J:["j","jay"],K:["k","kay"],L:["l","el","elle"],M:["m","em"],N:["n","en"],O:["o","oh"],P:["p","pee","pea"],Q:["q","cue","queue"],R:["r","ar","are"],S:["s","ess"],T:["t","tee","tea"],U:["u","you","yew"],V:["v","vee"],W:["w","double u","double you"],X:["x","ex"],Y:["y","why"],Z:["z","zed","zee"]};
function clean(value:string){return value.toLowerCase().replace(/[^a-z]/g,"")}

export default function AlphabetPage(){
 const router=useRouter(),audioCache=useRef(new Map<string,string>()),activeAudio=useRef<HTMLAudioElement|null>(null);
 const [busy,setBusy]=useState<string|null>(null),[done,setDone]=useState<Record<string,boolean>>({}),[messages,setMessages]=useState<Record<string,string>>({});
 async function listen(slug:string){if(busy)return;setBusy(slug);try{let url=audioCache.current.get(slug);if(!url){const response=await fetch("/api/tts",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({key:slug})});if(!response.ok)throw new Error();url=URL.createObjectURL(await response.blob());audioCache.current.set(slug,url)}const audio=new Audio(url);activeAudio.current=audio;audio.onended=()=>setBusy(null);audio.onerror=()=>setBusy(null);await audio.play()}catch{setBusy(null);setMessages(current=>({...current,[slug]:"Natural voice unavailable. Try again."}))}}
 function repeat(slug:string){if(busy)return;const lesson=alphabetLessons[slug],recognition=createSpeechRecognition();if(!recognition){setMessages(current=>({...current,[slug]:speechErrorMessage("unsupported")}));return}recognition.lang="en-GB";recognition.interimResults=false;recognition.maxAlternatives=10;setMessages(current=>({...current,[slug]:"Listening… say "+lesson.letter+"."}));recognition.onresult=(event:any)=>{const heard=Array.from(event.results[0]||[]).map((item:any)=>String(item.transcript||"").toLowerCase()),accepted=aliases[lesson.letter]||[lesson.letter.toLowerCase()],ok=heard.some(value=>accepted.includes(value.trim())||accepted.map(clean).includes(clean(value)));setDone(current=>({...current,[slug]:ok}));setMessages(current=>({...current,[slug]:ok?"✓ "+lesson.letter+" validated.":"I heard “"+(heard[0]||"")+"”. Listen and repeat."}))};recognition.onerror=(event)=>setMessages(current=>({...current,[slug]:speechErrorMessage(event?.error)}));recognition.start()}
 const completed=Object.values(done).filter(Boolean).length;
 return <main className="alphabet-page"><div className="alphabet-shell alphabet-library-shell"><div className="alphabet-topbar"><div className="lesson-pill">ALPHABET · 26 LETTERS</div><button className="exit-btn" onClick={()=>router.push("/welcome?overview=1")}>EXIT</button></div><section className="panel alphabet-library"><header><span className="eyebrow">LISTEN · REPEAT · REMEMBER</span><h1>The English alphabet</h1><p>All 26 letters are on one page. Listen to the natural voice, then repeat each letter.</p><div><b>{completed} / 26</b><small>VALIDATED</small></div></header><div className="alphabet-card-grid">{alphabetOrder.map(slug=>{const lesson=alphabetLessons[slug],message=messages[slug]||"Listen, then repeat.";return <article className={done[slug]?"alphabet-mini-card done":messages[slug]?"alphabet-mini-card attempted":"alphabet-mini-card"} key={slug}><div className="mini-letter"><b>{lesson.letter}</b><span>{lesson.lower}</span></div><strong>{lesson.ipa}</strong><small>as in {lesson.word}</small><div><button disabled={busy!==null} onClick={()=>listen(slug)}>🔊 {busy===slug?"PLAYING…":"LISTEN"}</button><button disabled={busy!==null} onClick={()=>repeat(slug)}>🎙 REPEAT</button></div><p>{message}</p></article>})}</div></section><footer className="footer-nav"><button className="nav3d" onClick={()=>router.push("/welcome?overview=1")}>‹ OVERVIEW</button><div className="progress"><span>{completed} / 26</span><div className="progress-track"><div className="progress-fill" style={{width:String(completed/26*100)+"%"}}/></div><span className="small">LETTERS VALIDATED</span></div><button className="nav3d next" onClick={()=>router.push("/alphabet/listen-identify")}>NEXT STEP ›</button></footer></div></main>
}
