"use client";
import {createSpeechRecognition,speechErrorMessage} from "@/lib/speech-recognition";

import {useEffect,useMemo,useRef,useState} from "react";
import {useRouter} from "next/navigation";
import "./dates.css";
import "./dates-theme.css";
import "./summary.css";

const days=["Monday","Tuesday","Wednesday","Thursday","Friday","Saturday","Sunday"];
const months=["January","February","March","April","May","June","July","August","September","October","November","December"];
const ordinals=["1st","2nd","3rd","4th","5th","6th","7th","8th","9th","10th","11th","12th","13th","14th","15th","16th","17th","18th","19th","20th","21st","22nd","23rd","24th","25th","26th","27th","28th","29th","30th","31st"];
const ordinalSpeech=["first","second","third","fourth","fifth","sixth","seventh","eighth","ninth","tenth","eleventh","twelfth","thirteenth","fourteenth","fifteenth","sixteenth","seventeenth","eighteenth","nineteenth","twentieth","twenty-first","twenty-second","twenty-third","twenty-fourth","twenty-fifth","twenty-sixth","twenty-seventh","twenty-eighth","twenty-ninth","thirtieth","thirty-first"];
const yearOptions=[{label:"1990",spoken:"nineteen ninety"},{label:"1998",spoken:"nineteen ninety-eight"},{label:"2000",spoken:"two thousand"},{label:"2005",spoken:"two thousand and five"},{label:"2025",spoken:"twenty twenty-five"},{label:"2026",spoken:"twenty twenty-six"},{label:"2050",spoken:"twenty fifty"}];
const formatExamples=[{written:"26 / 08 / 2026",spoken:"the twenty-sixth of August twenty twenty-six"},{written:"03 / 02 / 1998",spoken:"the third of February nineteen ninety-eight"},{written:"21 / 11 / 2005",spoken:"the twenty-first of November two thousand and five"},{written:"01 / 12 / 1999",spoken:"the first of December nineteen ninety-nine"},{written:"14 / 09 / 2026",spoken:"the fourteenth of September twenty twenty-six"},{written:"28 / 09 / 2026",spoken:"the twenty-eighth of September twenty twenty-six"},{written:"02 / 10 / 2026",spoken:"the second of October twenty twenty-six"},{written:"25 / 12 / 2025",spoken:"the twenty-fifth of December twenty twenty-five"}];
const quiz=[
  {say:"the twenty-sixth of August twenty twenty-six",options:["26 August 2026","16 August 2026","26 October 2026"],answer:"26 August 2026"},
  {say:"the third of February nineteen ninety-eight",options:["13 February 1998","3 February 1998","3 February 1989"],answer:"3 February 1998"},
  {say:"the twenty-first of November two thousand and five",options:["21 November 2005","20 November 2005","21 November 2015"],answer:"21 November 2005"},
  {say:"the first of December nineteen ninety-nine",options:["1 December 1999","11 December 1999","1 December 2009"],answer:"1 December 1999"},
  {say:"the fourteenth of September twenty twenty-six",options:["14 September 2026","40 September 2026","14 September 2016"],answer:"14 September 2026"},
  {say:"the twenty-eighth of September twenty twenty-six",options:["18 September 2026","28 September 2026","28 November 2026"],answer:"28 September 2026"},
  {say:"the second of October twenty twenty-six",options:["2 October 2026","12 October 2026","2 August 2026"],answer:"2 October 2026"},
  {say:"the twenty-fifth of December twenty twenty-five",options:["25 December 2025","15 December 2025","25 December 2026"],answer:"25 December 2025"},
];
const sayDateExamples=[{written:"13 / 01 / 2026",spoken:"the thirteenth of January twenty twenty-six"},{written:"26 / 08 / 2026",spoken:"the twenty-sixth of August twenty twenty-six"},{written:"01 / 12 / 1999",spoken:"the first of December nineteen ninety-nine"},{written:"03 / 02 / 1998",spoken:"the third of February nineteen ninety-eight"},{written:"21 / 11 / 2005",spoken:"the twenty-first of November two thousand and five"},{written:"14 / 09 / 2026",spoken:"the fourteenth of September twenty twenty-six"},{written:"02 / 10 / 2026",spoken:"the second of October twenty twenty-six"},{written:"25 / 12 / 2025",spoken:"the twenty-fifth of December twenty twenty-five"}];
const steps=["Welcome","Days & Months","Ordinals & Years","Date Formats","Listen & Identify","Say the Date","Real-Life Challenge","Results & Remediation","Validation"];
const stepDescriptions=["Start the module","Listen and repeat","Master 1st–31st and years","Read British dates","Choose the date you hear","Pronounce dates aloud","Take notes from a message","Review and practise","Complete the final check"];

async function speak(text:string){const response=await fetch("/api/symbol-tts",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({text,speed:.86})});if(!response.ok)throw new Error("Natural voice unavailable");const url=URL.createObjectURL(await response.blob()),audio=new Audio(url);audio.onended=()=>URL.revokeObjectURL(url);audio.onerror=()=>URL.revokeObjectURL(url);await audio.play()}
function normalize(s:string){return s.toLowerCase().replace(/[^a-z0-9 ]/g," ").replace(/\s+/g," ").trim()}
function canonicalSpeech(value:string){let text=value.toLowerCase().replace(/[’']/g,"").replace(/-/g," ");const years=[...yearOptions,{label:"1999",spoken:"nineteen ninety-nine"}].sort((a,b)=>b.spoken.length-a.spoken.length);years.forEach(year=>{text=text.replace(new RegExp(`\\b${year.spoken.replace(/-/g," ")}\\b`,"g"),year.label)});for(let index=ordinalSpeech.length-1;index>=0;index--){const word=ordinalSpeech[index].replace(/-/g," ");text=text.replace(new RegExp(`\\b${word}\\b`,"g"),String(index+1))}text=text.replace(/\b(\d{1,2})(st|nd|rd|th)\b/g,"$1").replace(/\b(its|is|the|of|on|date|and)\b/g," ");return normalize(text)}

export default function DatesModule(){
 const router=useRouter();const [step,setStep]=useState(1),[entered,setEntered]=useState(false),[learnIndex,setLearnIndex]=useState(0),[yearMode,setYearMode]=useState(false),[vocabLabel,setVocabLabel]=useState("1st"),[vocabSpoken,setVocabSpoken]=useState("first"),[formatIndex,setFormatIndex]=useState(0),[quizIndex,setQuizIndex]=useState(0),[choice,setChoice]=useState(""),[score,setScore]=useState(0),[sayIndex,setSayIndex]=useState(0),[heard,setHeard]=useState(""),[listening,setListening]=useState(false),[speechExpected,setSpeechExpected]=useState(""),[attempts,setAttempts]=useState(0),[notes,setNotes]=useState(""),[challengePlayed,setChallengePlayed]=useState(false),[challengeError,setChallengeError]=useState(""),[finalIndex,setFinalIndex]=useState(0),[finalScore,setFinalScore]=useState(0);const recognition=useRef<any>(null);
 useEffect(()=>{setEntered(true);speechSynthesis.getVoices()},[]);
 const speakTarget=sayDateExamples[sayIndex].spoken;
 const finalQuestions=useMemo(()=>[quiz[1],quiz[2],quiz[0]],[]);
 function go(n:number){setStep(Math.max(1,Math.min(9,n)));window.scrollTo({top:0,behavior:"smooth"})}
 function answerQuiz(v:string){if(choice)return;setChoice(v);if(v===quiz[quizIndex].answer)setScore(s=>s+1)}
 function nextQuiz(){if(quizIndex<quiz.length-1){setQuizIndex(i=>i+1);setChoice("")}else go(6)}
 const vocabOrdinalIndex=ordinals.indexOf(vocabLabel),vocabYearIndex=yearOptions.findIndex(year=>year.label===vocabLabel);
 function footerPosition(){if(step===2)return{index:(yearMode?days.length:0)+learnIndex,total:days.length+months.length,label:yearMode?"MONTH":"DAY"};if(step===3)return{index:vocabOrdinalIndex>=0?vocabOrdinalIndex:ordinals.length+Math.max(0,vocabYearIndex),total:ordinals.length+yearOptions.length,label:vocabOrdinalIndex>=0?"ORDINAL":"YEAR"};if(step===4)return{index:formatIndex,total:formatExamples.length,label:"DATE"};if(step===5)return{index:quizIndex,total:quiz.length,label:"DATE"};if(step===6)return{index:sayIndex,total:sayDateExamples.length,label:"DATE"};return{index:-1,total:0,label:"ITEM"}}
 function setFooterItem(index:number){setHeard("");setSpeechExpected("");if(step===2){if(index<days.length){setYearMode(false);setLearnIndex(index)}else{setYearMode(true);setLearnIndex(index-days.length)}}if(step===3){if(index<ordinals.length){setVocabLabel(ordinals[index]);setVocabSpoken(ordinalSpeech[index])}else{const year=yearOptions[index-ordinals.length];setVocabLabel(year.label);setVocabSpoken(year.spoken)}}if(step===4)setFormatIndex(index);if(step===5){setQuizIndex(index);setChoice("")}if(step===6)setSayIndex(index)}
 function footerPrevious(){const item=footerPosition();if(item.index>0){setFooterItem(item.index-1);return}go(step-1)}
 function footerNext(){const item=footerPosition();if(item.index>=0&&item.index<item.total-1){setFooterItem(item.index+1);return}go(step+1)}
 const footerItem=footerPosition();
 function record(target:unknown=speakTarget){const expected=typeof target==="string"?target:speakTarget,r=createSpeechRecognition();if(!r){setHeard(speechErrorMessage("unsupported"));return}setSpeechExpected(expected);recognition.current=r;r.lang="en-GB";r.interimResults=false;r.continuous=false;setListening(true);setHeard("");r.onresult=(e:any)=>{const text=e.results[0][0].transcript;setHeard(text);setAttempts(a=>a+1);setListening(false)};r.onerror=(event)=>{setHeard(speechErrorMessage(event?.error));setListening(false)};r.onend=()=>setListening(false);r.start()}
 const heardCanonical=canonicalSpeech(heard),expectedCanonical=canonicalSpeech(speechExpected),spokenOk=!!heardCanonical&&(heardCanonical===expectedCanonical||heardCanonical.includes(expectedCanonical)||expectedCanonical.includes(heardCanonical));
 async function playChallenge(){setChallengePlayed(true);setChallengeError("");try{await speak("Good morning. Please note the following training dates. The registration deadline is the fourteenth of September twenty twenty-six. The assessment is on the twenty-eighth of September twenty twenty-six, and the results will be available on the second of October twenty twenty-six.")}catch{setChallengeError("The message could not be played. Please try again.")}}
 function finalAnswer(v:string){const q=finalQuestions[finalIndex];if(v===q.answer)setFinalScore(s=>s+1);if(finalIndex<2)setFinalIndex(i=>i+1);else setTimeout(()=>go(9),200)}
 return <main className="dates-page"><div className="dates-shell"><header className="dates-top"><div><span>CADGA · MODULE 04</span><strong>DATES &amp; SPEAKING</strong></div><div className="date-progress"><i><em style={{width:`${step/9*100}%`}}/></i><small>STEP {step} / 9</small></div><button onClick={()=>router.push("/")}>EXIT</button></header>
 {step===1&&(!entered?<section className="dates-card welcome date-enter"><div className="welcome-copy"><span>WELCOME</span><h1>DATES<br/><b>&amp; SPEAKING</b></h1><p>Learn to understand, read and pronounce dates clearly in professional English.</p><button className="date-primary" onClick={()=>setEntered(true)}>ENTER MODULE</button></div><div className="calendar-visual"><small>AUGUST 2026</small><b>26</b><span>WEDNESDAY</span></div></section>:<section className="dates-card date-summary"><span>WELCOME</span><h1>DATES &amp; SPEAKING</h1><p>Choose any step below to review the module. Listen to the natural voice and practise professional dates.</p><div className="summary-meta"><div><b>◷</b><span>ESTIMATED TIME<small>30–35 MIN</small></span></div><div><b>★</b><span>FINAL VALIDATION<small>80% TARGET</small></span></div><div><b>🎙</b><span>MICROPHONE<small>SPEAKING PRACTICE</small></span></div></div><div className="overview summary-steps"><h2>MODULE OVERVIEW</h2>{steps.slice(1).map((s,i)=><button key={s} onClick={()=>go(i+2)}><b>{String(i+1).padStart(2,"0")}</b><span><strong>{s}</strong><small>{stepDescriptions[i+1]}</small></span><em>0%</em></button>)}</div></section>)}
 {step===2&&<section className="dates-card lesson"><div className="lesson-head"><span>LISTEN · REPEAT · REMEMBER</span><h1>Days &amp; Months</h1><p>Select a card, listen to the natural English voice, then repeat aloud.</p><div className="segmented"><button className={!yearMode?"active":""} onClick={()=>{setYearMode(false);setLearnIndex(0);setHeard("")}}>DAYS</button><button className={yearMode?"active":""} onClick={()=>{setYearMode(true);setLearnIndex(0);setHeard("")}}>MONTHS</button></div></div><div className="date-focus"><small>{yearMode?"MONTH OF THE YEAR":"DAY OF THE WEEK"}</small><b>{yearMode?months[learnIndex]:days[learnIndex]}</b><div className="listen-repeat-actions"><button onClick={()=>speak(yearMode?months[learnIndex]:days[learnIndex])}>🔊 LISTEN</button><button className="repeat-action" onClick={()=>record(yearMode?months[learnIndex]:days[learnIndex])}>🎙 REPEAT</button></div>{heard&&speechExpected===(yearMode?months[learnIndex]:days[learnIndex])&&<div className={spokenOk?"transcript good":"transcript"}><small>I HEARD</small><b>“{heard}”</b><span>{spokenOk?"✓ Correct — pronunciation validated.":"Listen again, then repeat."}</span></div>}</div><div className="date-grid">{(yearMode?months:days).map((v,i)=><button className={learnIndex===i?"active":""} key={v} onClick={()=>{setLearnIndex(i);setHeard("")}}>{v}</button>)}</div></section>}
 {step===3&&<section className="dates-card lesson"><div className="lesson-head"><span>BUILD YOUR DATE VOCABULARY</span><h1>Ordinals &amp; Years</h1><p>Choose an ordinal or a year, listen to the natural voice, then repeat it into your microphone.</p></div><div className="vocab-practice"><small>SELECTED</small><b>{vocabLabel}</b><span>{vocabSpoken}</span><div className="listen-repeat-actions"><button onClick={()=>speak(vocabSpoken)}>🔊 LISTEN</button><button className="repeat-action" onClick={()=>record(vocabSpoken)}>🎙 REPEAT</button></div>{heard&&speechExpected===vocabSpoken&&<div className={spokenOk?"transcript good":"transcript"}><small>I HEARD</small><b>“{heard}”</b><span>{spokenOk?"✓ Correct — pronunciation validated.":"Listen again, then repeat."}</span></div>}</div><div className="ordinal-grid">{ordinals.map((o,i)=><button className={vocabLabel===o?"active":""} key={o} onClick={()=>{setVocabLabel(o);setVocabSpoken(ordinalSpeech[i]);setHeard("")}}>{o}<span>{ordinalSpeech[i]}</span></button>)}</div><div className="years"><h2>Practise years</h2>{yearOptions.map(y=><button className={vocabLabel===y.label?"active":""} key={y.label} onClick={()=>{setVocabLabel(y.label);setVocabSpoken(y.spoken);setHeard("")}}>{y.label}</button>)}</div></section>}
 {step===4&&<section className="dates-card format format-many"><div><span>BRITISH ENGLISH</span><h1>Read dates<br/>the CADGA way.</h1><p>Use the British order: <b>day + month + year</b>. Select each date, listen, then repeat.</p><div className="format-how"><b>1. SELECT</b><span>Choose one of the dates below.</span><b>2. LISTEN</b><span>Hear the complete British date.</span><b>3. REPEAT</b><span>Say it into your microphone.</span></div><div className="format-list">{formatExamples.map((example,index)=><button className={formatIndex===index?"active":""} key={example.written} onClick={()=>{setFormatIndex(index);setHeard("")}}>{example.written}</button>)}</div></div><div className="format-demo"><small>WRITTEN DATE · {formatIndex+1} / {formatExamples.length}</small><strong>{formatExamples[formatIndex].written}</strong><div><b>DD<span>DAY</span></b><b>MM<span>MONTH</span></b><b>YYYY<span>YEAR</span></b></div><p>{formatExamples[formatIndex].spoken}</p><div className="listen-repeat-actions"><button onClick={()=>speak(formatExamples[formatIndex].spoken)}>🔊 LISTEN</button><button className="repeat-action" onClick={()=>record(formatExamples[formatIndex].spoken)}>🎙 REPEAT</button></div>{heard&&speechExpected===formatExamples[formatIndex].spoken&&<div className={spokenOk?"transcript good":"transcript"}><small>I HEARD</small><b>“{heard}”</b><span>{spokenOk?"✓ Correct — complete date validated.":"Listen to the model, then repeat the complete date."}</span></div>}</div></section>}
 {step===5&&<section className="dates-card quiz"><div className="quiz-title"><span>LISTEN &amp; IDENTIFY · 8 AUDIO QUESTIONS</span><h1>Which date did you hear?</h1><b>{quizIndex+1} / {quiz.length}</b></div><div className="quiz-slide-tabs">{quiz.map((_,index)=><button className={quizIndex===index?"active":""} key={index} onClick={()=>{setQuizIndex(index);setChoice("")}}>{index+1}</button>)}</div><button className="listen-orb" onClick={()=>speak(quiz[quizIndex].say)}>🔊<span>PLAY AUDIO {quizIndex+1}</span></button><div className="date-options">{quiz[quizIndex].options.map(v=><button key={v} className={choice?v===quiz[quizIndex].answer?"correct":v===choice?"wrong":"":""} onClick={()=>answerQuiz(v)}>{v}</button>)}</div>{choice&&<div className="feedback">{choice===quiz[quizIndex].answer?"✓ Correct — well done!":"Not quite. Listen once more and compare the day, month and year."}<button onClick={nextQuiz}>{quizIndex===quiz.length-1?"CONTINUE":"NEXT DATE"} →</button></div>}</section>}
 {step===6&&<section className="dates-card speak"><span>SAY THE DATE · 8 DATES TO COMPLETE</span><h1>{sayDateExamples[sayIndex].written}</h1><p>Choose a date below and say it in British English. Only the numeric date is shown.</p><div className="say-date-grid">{sayDateExamples.map((example,index)=><button className={sayIndex===index?"active":""} key={example.written} onClick={()=>{setSayIndex(index);setHeard("");setSpeechExpected("")}}><small>{index+1}</small>{example.written}</button>)}</div><button className={listening?"mic listening":"mic"} onClick={record}>🎙<small>{listening?"LISTENING…":"SAY DATE " +(sayIndex+1)}</small></button>{heard&&<div className={spokenOk?"transcript good":"transcript"}><small>I HEARD</small><b>“{heard}”</b><span>{spokenOk?"✓ Good pronunciation":"Try the complete date again."}</span></div>}<div className="say-navigation"><button disabled={sayIndex===0} onClick={()=>{setSayIndex(i=>Math.max(0,i-1));setHeard("")}}>← PREVIOUS</button><b>{sayIndex+1} / {sayDateExamples.length}</b><button disabled={sayIndex===sayDateExamples.length-1} onClick={()=>{setSayIndex(i=>Math.min(sayDateExamples.length-1,i+1));setHeard("")}}>NEXT →</button></div></section>}
 {step===7&&<section className="dates-card challenge"><div><span>REAL-LIFE CHALLENGE</span><h1>Take note of the dates.</h1><p>Listen to this professional message. Write only the three important dates in your notes.</p><button className="date-primary" onClick={playChallenge}>🔊 {challengePlayed?"PLAY AGAIN":"PLAY MESSAGE"}</button>{challengeError&&<p className="audio-error">{challengeError}</p>}</div><label>YOUR NOTES<textarea value={notes} onChange={e=>setNotes(e.target.value)} placeholder="Write the dates here…"/></label>{challengePlayed&&!challengeError&&notes.trim().length>5&&<details><summary>CHECK THE CORRECTION</summary><p>Registration deadline: <b>14 September 2026</b><br/>Assessment: <b>28 September 2026</b><br/>Results: <b>2 October 2026</b></p></details>}</section>}
 {step===8&&<section className="dates-card results"><span>RESULTS &amp; REMEDIATION</span><h1>Your date profile</h1><div className="score-ring" style={{background:`conic-gradient(#38d9a9 ${(score/3)*360}deg,#173b3a 0)`}}><b>{Math.round(score/3*100)}%</b></div><div className="result-stats"><div><b>{score}/3</b><span>LISTENING</span></div><div><b>{attempts}</b><span>SPEAKING ATTEMPTS</span></div><div><b>{challengePlayed?"DONE":"—"}</b><span>REAL-LIFE TASK</span></div></div><p>{score<3?"Replay the listening activity to strengthen day, month and year recognition.":"Excellent listening accuracy. You are ready for the final validation."}</p><button className="date-secondary" onClick={()=>go(score<2?5:9)}>{score<2?"REVIEW LISTENING":"START VALIDATION"} →</button></section>}
 {step===9&&<section className="dates-card validation">{finalIndex<3?<><span>FINAL VALIDATION · QUESTION {finalIndex+1}/3</span><h1>Listen and choose.</h1><button className="listen-orb" onClick={()=>speak(finalQuestions[finalIndex].say)}>🔊<span>PLAY AUDIO</span></button><div className="date-options">{finalQuestions[finalIndex].options.map(v=><button key={v} onClick={()=>finalAnswer(v)}>{v}</button>)}</div></>:<><div className="award">★</div><span>MODULE 04 COMPLETE</span><h1>{finalScore>=2?"ACQUIRED":"KEEP PRACTISING"}</h1><p>You scored {finalScore}/3. {finalScore>=2?"You can understand and pronounce dates in a professional context.":"Review the listening activities, then try the validation again."}</p><button className="date-primary" onClick={()=>router.push("/")}>BACK TO MY JOURNEY</button></>}</section>}
 {step>1&&step<9&&<footer className="dates-footer"><button onClick={footerPrevious}>‹ {footerItem.index>0?`PREVIOUS ${footerItem.label}`:"PREVIOUS"}</button><span>{steps[step-1].toUpperCase()}{footerItem.index>=0&&` · ${footerItem.index+1} / ${footerItem.total}`}</span><button className="date-primary" onClick={footerNext}>{footerItem.index>=0&&footerItem.index<footerItem.total-1?`NEXT ${footerItem.label} →`:"NEXT STEP →"}</button></footer>}
 </div></main>
}
