"use client";
import {useEffect,useRef,useState} from "react";
import {useRouter} from "next/navigation";
import "../alphabet.css";
import {createSpellingRecognition,speechErrorMessage} from "@/lib/speech-recognition";

const names=["WILSON","JACKSON","MARTIN","ANDERSON","THOMAS","MORGAN","TAYLOR","BENNETT"];
const css=`.sp{max-width:1050px;margin:auto}.spCard{padding:38px;text-align:center}.spHead{text-align:left}.spHead h1{font-size:36px;margin:8px 0}.spHead p{color:#b9c2e5;margin:0}.spName{margin:34px auto 10px;max-width:680px;padding:28px;border:1px solid #4c58a4;border-radius:22px;background:linear-gradient(180deg,#202958,#111735);box-shadow:0 12px 30px #0005}.spName small{display:block;color:#aeb8df;font-weight:800;letter-spacing:.12em}.spName strong{display:block;font-size:64px;letter-spacing:.12em;margin-top:10px}.spHint{color:#b9c2e5;margin:12px 0 25px}.spMic{width:180px;height:180px;border:0;border-radius:50%;color:#fff;background:radial-gradient(circle at 35% 25%,#d26aff,#7439dc 58%,#3b208f);box-shadow:0 11px 0 #28166d,0 24px 45px #0007,0 0 40px #9d55ff55;cursor:pointer;font-weight:900}.spMic span{display:block;font-size:48px}.spMic b{display:block;margin-top:8px;font-size:17px}.spMic.rec{animation:pulse 1s infinite;background:radial-gradient(circle at 35% 25%,#ff6b9d,#d83873 58%,#7b1c48)}@keyframes pulse{50%{transform:scale(1.04);box-shadow:0 11px 0 #5c1639,0 24px 45px #0007,0 0 65px #ff559988}}.spHeard{max-width:680px;margin:28px auto 0;padding:18px;border:1px solid #343c76;border-radius:16px;background:#0a1025;min-height:62px}.spHeard small{display:block;color:#9da8d3;font-size:11px;letter-spacing:.1em;font-weight:900}.spHeard strong{display:block;margin-top:7px;font-size:21px}.spHeard.good{border-color:#32c98a;color:#8df0c6}.spHeard.bad{border-color:#ef6f87;color:#ffb3c0}.spBottom{display:flex;align-items:center;gap:18px;margin-top:30px}.spProg{flex:1;display:flex;align-items:center;gap:12px;color:#cbd1ee}.spTrack{height:8px;flex:1;background:#252b53;border-radius:20px;overflow:hidden}.spFill{height:100%;background:linear-gradient(90deg,#7a55ff,#c766ff)}.spResult{padding:55px;text-align:center}.spResult h1{font-size:42px}.spRing{width:180px;height:180px;border-radius:50%;margin:0 auto 25px;display:grid;place-items:center;font-size:42px;font-weight:900;background:radial-gradient(circle,#151b3d 56%,transparent 58%),conic-gradient(#65d5aa 0 var(--p),#303761 var(--p));box-shadow:0 0 45px #5e65ff44}@media(max-width:650px){.spCard{padding:20px}.spHead h1{font-size:28px}.spName strong{font-size:43px}.spMic{width:145px;height:145px}.spBottom{flex-wrap:wrap}.spProg{order:-1;flex-basis:100%}}`;

function clean(s:string){return s.toUpperCase().replace(/[^A-Z]/g,"")}
const letterWords:Record<string,string>={a:"A",ay:"A",aye:"A",b:"B",bee:"B",c:"C",see:"C",sea:"C",d:"D",dee:"D",e:"E",ee:"E",f:"F",eff:"F",g:"G",gee:"G",h:"H",aitch:"H",i:"I",eye:"I",j:"J",jay:"J",k:"K",kay:"K",l:"L",el:"L",m:"M",em:"M",n:"N",en:"N",o:"O",oh:"O",p:"P",pee:"P",q:"Q",cue:"Q",queue:"Q",r:"R",are:"R",s:"S",ess:"S",t:"T",tee:"T",tea:"T",u:"U",you:"U",yew:"U",v:"V",vee:"V",w:"W",doubleyou:"W",x:"X",ex:"X",y:"Y",why:"Y",z:"Z",zed:"Z",zee:"Z"};
function spokenLetters(s:string){const normalized=s.toLowerCase().replace(/double\s+you/g,"doubleyou").replace(/[^a-z]+/g," ").trim();if(!normalized)return "";return normalized.split(/\s+/).map(x=>letterWords[x]||((x.length===1&&/[a-z]/.test(x))?x.toUpperCase():"")).join("")}

// Strict: every letter must be right (G-A-C-K-S-O-N is not JACKSON). The name said as one word does not count as spelling.
function matchesSpelling(transcript:string,target:string){const tokens=transcript.trim().split(/[^A-Za-z]+/).filter(Boolean);if(tokens.length<2)return false;return spokenLetters(transcript)===target||clean(transcript)===target}

export default function SpellIt(){const router=useRouter();const[i,setI]=useState(0);const[heard,setHeard]=useState("");const[done,setDone]=useState(false);const[ok,setOk]=useState<boolean|null>(null);const[score,setScore]=useState(0);const[finished,setFinished]=useState(false);const[listening,setListening]=useState(false);const rec=useRef<any>(null);const target=names[i];
useEffect(()=>()=>{try{rec.current?.abort?.()}catch{}},[]);
function record(){if(done||listening)return;if(typeof window!=="undefined"&&!window.isSecureContext){setHeard(speechErrorMessage("insecure"));setOk(false);return}const r:any=createSpellingRecognition("en-GB");if(!r){setHeard("Voice recognition is not supported in this browser. Try the latest Chrome, Edge or Safari.");setOk(false);return}rec.current=r;setListening(true);r.onphase=(phase:string)=>{if(phase==="transcribing")setHeard("Checking your spelling…")};r.onend=()=>setListening(false);r.maxAlternatives=10;r.onstart=()=>setHeard("Listening… spell the name letter by letter, then pause.");r.onerror=(e:any)=>{setHeard(speechErrorMessage(e?.error));setOk(false);setDone(false)};r.onresult=(e:any)=>{const alts=Array.from(e.results[0] as any).map((x:any)=>x.transcript as string);const match=alts.some(x=>matchesSpelling(x,target));const best=alts[0]||"";setHeard(best);setOk(match);setDone(true);if(match)setScore(s=>s+1)};try{r.start()}catch{setHeard("Voice recognition could not start. Check microphone permission and try again.");setOk(false);setDone(false)}}
function next(){if(i===names.length-1){setFinished(true);return}setI(x=>x+1);setHeard("");setDone(false);setOk(null)}function retry(){setHeard("");setDone(false);setOk(null)}
if(finished){const pct=Math.round(score/names.length*100);return <main className="alphabet-page"><style>{css}</style><div className="sp"><div className="alphabet-topbar"><div className="lesson-pill">STEP 5 / 10 · SPELL IT</div><button className="exit-btn" onClick={()=>router.push('/alphabet')}>EXIT</button></div><section className="panel spResult"><div className="spRing" style={{"--p":`${pct}%`} as any}>{pct}%</div><span className="eyebrow">VOICE SPELLING COMPLETE</span><h1>{pct>=75?"GREAT SPELLING!":"KEEP PRACTISING"}</h1><p>You spelled <strong>{score} / {names.length}</strong> customer names correctly.</p><div className="identify-actions"><button className="nav3d" onClick={()=>{setI(0);setScore(0);setFinished(false);setDone(false);setOk(null);setHeard("")}}>↻ TRY AGAIN</button><button className="nav3d next" onClick={()=>router.push('/alphabet/listen-type')}>CONTINUE ›</button></div></section></div></main>}
return <main className="alphabet-page"><style>{css}</style><div className="sp"><div className="alphabet-topbar"><div className="lesson-pill">STEP 5 / 10 · SPELL IT</div><button className="exit-btn" onClick={()=>router.push('/alphabet')}>EXIT</button></div><section className="panel spCard"><div className="spHead"><span className="eyebrow">CUSTOMER NAME · {i+1} OF {names.length}</span><h1>SPELL IT OUT LOUD.</h1><p>Read the customer name, then spell it letter by letter into your microphone.</p></div><div className="spName"><small>CUSTOMER NAME</small><strong>{target}</strong></div><p className="spHint">Example: WILSON → W · I · L · S · O · N</p><button className={`spMic ${listening?"rec":""}`} onClick={record} disabled={done||listening}><span>🎙️</span><b>{listening?(heard==="Checking your spelling…"?"CHECKING…":"LISTENING…"):"RECORD SPELLING"}</b></button><div className={`spHeard ${ok===true?"good":ok===false?"bad":""}`}><small>WHAT I HEARD</small><strong>{heard||"Your spelling will appear here."}</strong>{ok===true&&<div>✓ Correct spelling</div>}{ok===false&&done&&<div>{/^[A-Za-z]+[.!?]?$/.test(heard.trim())?`That sounds like the whole word. Spell it letter by letter: ${target.split("").join(" · ")}.`:`Not quite. Spell ${target} again.`}</div>}</div><div className="spBottom"><button className="nav3d" onClick={()=>router.push('/alphabet/confusing-letters')}>‹ STEP 4</button><div className="spProg"><span>{i+1} / {names.length}</span><div className="spTrack"><div className="spFill" style={{width:`${((i+(done?1:0))/names.length)*100}%`}}/></div></div>{done&&ok===false?<button className="nav3d next" onClick={retry}>TRY AGAIN ↻</button>:<button className="nav3d next" disabled={!done||!ok} onClick={next}>{i===names.length-1?"SEE RESULTS ›":"NEXT ›"}</button>}</div></section></div></main>}
