import Link from "next/link";
import "./modules-extra.css";
import "../infinity-signature.css";

const modules=[
 {number:"01",title:"Alphabet & Spelling",description:"Recognise, pronounce and spell names accurately.",href:"/welcome?overview=1",color:"alphabet",icon:"Aa",activities:"9 activities"},
 {number:"02",title:"Numbers & Speaking",description:"Understand and pronounce numbers up to one billion.",href:"/numbers/welcome?overview=1",color:"numbers",icon:"123",activities:"8 activities"},
 {number:"03",title:"Symbols & Special Characters",description:"Capture email addresses and essential written symbols.",href:"/symbols/welcome?overview=1",color:"amber",icon:"@#",activities:"9 activities"},
 {number:"04",title:"Dates & Speaking",description:"Read, understand and pronounce British dates.",href:"/dates/welcome",color:"dates",icon:"26",activities:"8 activities"},
 {number:"05",title:"Time & Telling the Time",description:"Understand, ask for and give professional times.",href:"/time/welcome",color:"symbols",icon:"10:10",activities:"8 activities"},
];

export default function Modules(){return <main className="cadga-home modules-page"><header className="home-nav modules-nav"><Link className="home-brand" href="/"><span>A</span><div><strong>AD</strong><small>ENGLISH LEARNING</small></div></Link><Link className="back-home" href="/days"><i>←</i> MAIN MENU</Link></header><section className="home-modules"><div className="modules-heading"><div><span>DAY 01 · THE FOUNDATIONS</span><h1>Your first five modules</h1><p>Listen, repeat, practise and validate each essential skill.</p></div><div className="modules-progress"><span>5 MODULES AVAILABLE</span><i><em/></i></div></div><div className="home-module-grid compact-modules">{modules.map(module=><Link className={`home-module ${module.color}`} href={module.href} key={module.number}><div className="module-visual"><div className="module-banner-top"><small>MODULE {module.number}</small><b>0% COMPLETE</b></div><h3>{module.title}</h3><span>OPEN MODULE ↗</span></div><div className="module-copy"><span>{module.activities}</span><p>{module.description}</p><div><b>START LEARNING</b><i>→</i></div></div></Link>)}</div><div className="day-games"><section className="casino-invite"><div><span>DAY 01 · VOCABULARY CHALLENGE</span><h2>Enter the CADGA Casino.</h2><p>Twenty professional vocabulary hands. €100 in chips. One final All-in.</p></div><div className="casino-invite-chips"><i>€5</i><i>€20</i><i>€50</i></div><Link href="/casino">ENTER THE CASINO <b>→</b></Link></section><section className="timesup-invite"><div><span>DAY 01 · TEAM CHALLENGE</span><h2>Time’s Up CADGA.</h2><p>Thirty cards. Three ways to make you guess.</p></div><div className="timesup-rounds"><i>DESCRIBE IT</i><i>ONE WORD</i><i>DRAWING</i></div><Link href="/times-up">SPIN FOR A TEAM <b>→</b></Link></section></div></section><footer className="home-footer"><div className="home-brand compact"><span>A</span><div><strong>AD</strong><small>LEARNING STUDIO</small></div></div><p>English for confident, professional customer interactions.</p><small>CREATED BY <b>ALEXANDRE AND MURIEL</b></small></footer></main>}
