"use client";
import { useMemo, useRef, useState } from "react";
import { useRouter } from "next/navigation";
import "../alphabet.css";
const rounds=[{answer:"A",choices:["A","E","I","Y"]},{answer:"F",choices:["F","S","X","V"]},{answer:"N",choices:["N","M","L","R"]},{answer:"T",choices:["T","D","P","G"]},{answer:"J",choices:["J","G","K","H"]},{answer:"I",choices:["I","E","Y","A"]},{answer:"B",choices:["B","P","V","D"]},{answer:"R",choices:["R","A","O","L"]},{answer:"U",choices:["U","Q","W","O"]},{answer:"X",choices:["X","S","F","Z"]}];
function shuffle<T>(items:T[]){const copy=[...items];for(let i=copy.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[copy[i],copy[j]]=[copy[j],copy[i]]}return copy}
export default function ListenIdentifyPage(){const router=useRouter();const[round,setRound]=useState(0);const[selected,setSelected]=useState<string|null>(null);const[answered,setAnswered]=useState(false);const[score,setScore]=useState(0);const[errors,setErrors]=useState<Record<string,number>>({});const[audioBusy,setAudioBusy]=useState(false);const[finished,setFinished]=useState(false);const cache=useRef(new Map<string,string>());const current=rounds[round];const progress=finished?100:((round+(answered?1:0))/rounds.length)*100;const shuffled=useMemo(()=>shuffle(current?.choices||[]),[round]);
async function listen(){if(audioBusy||finished)return;try{setAudioBusy(true);const key=`identify-${current.answer.toLowerCase()}`;let url=cache.current.get(key);if(!url){const response=await fetch("/api/tts",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({key})});if(!response.ok)throw new Error("Audio unavailable");const blob=await response.blob();url=URL.createObjectURL(blob);cache.current.set(key,url)}const audio=new Audio(url);audio.onended=()=>setAudioBusy(false);audio.onerror=()=>setAudioBusy(false);await audio.play()}catch{setAudioBusy(false)}}
function choose(letter:string){if(answered||audioBusy||finished)return;setSelected(letter);setAnswered(true);if(letter===current.answer)setScore(s=>s+1);else setErrors(e=>({...e,[current.answer]:(e[current.answer]||0)+1}))}
function nextRound(){if(!answered)return;if(round===rounds.length-1){setFinished(true);return}setRound(r=>r+1);setSelected(null);setAnswered(false)}
if(finished){const pct=Math.round((score/rounds.length)*100);const difficult=Object.keys(errors);return <main className="alphabet-page"><div className="alphabet-shell identify-shell"><div className="alphabet-topbar"><div className="lesson-pill">STEP 3 / 10 · LISTEN & IDENTIFY</div><button className="exit-btn" onClick={()=>router.push("/alphabet")}>EXIT</button></div><section className="panel identify-result"><div className="result-ring" style={{backgroundImage:`radial-gradient(circle,#151b3d 56%,transparent 58%),conic-gradient(#65d5aa ${pct}%,#303761 0)`}}>{pct}%</div><h1>{pct>=80?"GREAT LISTENING!":"LET’S PRACTICE A LITTLE MORE"}</h1><p>You identified <strong>{score} / {rounds.length}</strong> letters correctly.</p>{difficult.length>0&&<div className="difficulty-box"><span>LETTERS TO WATCH</span><strong>{difficult.join(" · ")}</strong></div>}<div className="identify-actions"><button className="nav3d" onClick={()=>{setRound(0);setSelected(null);setAnswered(false);setScore(0);setErrors({});setFinished(false)}}>↻ TRY AGAIN</button><button className="nav3d next" onClick={()=>router.push("/alphabet/confusing-letters")}>CONTINUE ›</button></div></section></div></main>}
const correct=selected===current.answer;return <main className="alphabet-page"><div className="alphabet-shell identify-shell"><div className="alphabet-topbar"><div className="lesson-pill">STEP 3 / 10 · LISTEN & IDENTIFY</div><button className="exit-btn" onClick={()=>router.push("/alphabet")}>EXIT</button></div><section className="panel identify-panel"><div className="identify-head"><div><span className="eyebrow">QUESTION {round+1} OF {rounds.length}</span><h1>WHICH LETTER DID YOU HEAR?</h1><p>Listen carefully, then select the correct letter.</p></div><div className="score-chip">SCORE <strong>{score}</strong></div></div><button className={`listen-orb ${audioBusy?"loading":""}`} disabled={audioBusy||answered} onClick={listen}><span>🔊</span><b>{audioBusy?"PLAYING…":"LISTEN"}</b><small>You can listen before answering</small></button><div className="identify-choices">{shuffled.map(letter=>{const isSelected=selected===letter,isCorrect=answered&&letter===current.answer,isWrong=answered&&isSelected&&letter!==current.answer;return <button key={letter} disabled={answered||audioBusy} onClick={()=>choose(letter)} className={`letter-choice ${isCorrect?"correct":""} ${isWrong?"wrong":""}`}>{letter}{isCorrect&&<span>✓</span>}{isWrong&&<span>×</span>}</button>})}</div><div className={`identify-feedback ${answered?(correct?"good":"bad"):""}`}>{!answered?"Listen first. Choose only when you are ready.":correct?`✓ Correct — you heard ${current.answer}.`:`Not quite — the correct letter was ${current.answer}.`}</div><div className="identify-bottom"><button className="nav3d" onClick={()=>router.push("/alphabet/z")}>‹ BACK TO LEARN</button><div className="identify-progress"><span>{round+1} / {rounds.length}</span><div className="progress-track"><div className="progress-fill" style={{width:`${progress}%`}}/></div></div><button className="nav3d next" disabled={!answered} onClick={nextRound}>{round===rounds.length-1?"SEE RESULTS ›":"NEXT ›"}</button></div></section></div></main>}
