import {storedVoice} from "@/lib/voice-store";
import { NextResponse } from "next/server";
import { alphabetLessons } from "@/lib/alphabet-data";
const scripts:Record<string,string>={};for(const[slug,lesson]of Object.entries(alphabetLessons)){scripts[slug]=lesson.spoken;scripts[`identify-${slug}`]=lesson.spoken;scripts[`${slug}-as-in`]=`${lesson.letter} as in ${lesson.word}.`;for(const example of lesson.examples)scripts[example.key]=`${example.label}.`}
scripts["identify-a"]="A.";scripts["identify-f"]="eff.";scripts["identify-n"]="en.";scripts["identify-t"]="tee.";scripts["identify-j"]="jay.";scripts["identify-r"]="are.";
const confusingNames:Record<string,string>={a:"A.",s:"ess.",i:"eye.",k:"kay.",j:"jay.",b:"bee.",p:"pee.",f:"eff.",l:"el.",n:"en.",u:"you.",q:"cue."};for(const[letter,name]of Object.entries(confusingNames))scripts[`confusing-${letter}`]=name;
const listenTypeNames:Record<string,string>={jackson:"J. A. C. K. S. O. N.",morgan:"M. O. R. G. A. N.",bennett:"B. E. N. N. E. T. T.",wilson:"double you. eye. el. ess. oh. en.",taylor:"T. A. Y. L. O. R.",martin:"M. A. R. T. eye. N.",anderson:"A. N. D. E. R. S. O. N.",thomas:"T. H. O. M. A. S."};for(const[name,spelling]of Object.entries(listenTypeNames))scripts[`listen-type-${name}`]=spelling;
scripts["real-life-message"]="Hi. I have four customer names for the follow-up list. First: see. A. are. tee. E. are. Second: pee. H. eye. el. el. eye. pee. ess. Third: gee. oh. em. E. zee. And the last one: H. you. gee. H. E. ess. Please add all four names to the customer record. Thank you.";
scripts["welcome-intro"]="Welcome to Alphabet and Spelling. In this module, you will develop the listening and spelling reflexes needed to capture customer information accurately and confidently.";
scripts["a-as-in-apple"]="A as in Apple.";scripts["amelia-anderson"]="Amelia Anderson.";scripts["administrative-assistant"]="Administrative Assistant.";scripts["atlas-services"]="Atlas Services.";scripts["australia"]="Australia.";scripts["amsterdam"]="Amsterdam.";

// Messages vocaux téléchargeables (MES CADGA / Pitch Vision), avec leur propre voix. GET /api/tts?key=...
const voiceFor:Record<string,string>={};const downloadable=new Set<string>();
scripts["pv-stridex-voicemail"]="Hello, this is David Miller, Marketing Manager at Stridex Sportswear in New York. I'm calling about our LED advertising campaign during the France versus Brazil match at the Stade de France last Saturday, the first of August. Unfortunately, our advertisement was only displayed during the first half of the match. It completely disappeared after halftime, even though we booked your P V zero one perimeter screens package for the whole match. This is a serious issue for our international campaign, and we are very disappointed. Could Mr Thomas Dubois, your Commercial Director, please call me back as soon as possible to discuss this? You can reach me directly on... plus one... two, one, two... five, five, five... zero, one, four, seven. Or by email at... david, dot, miller, at, stridexsports, dot, com. Thank you very much. Goodbye.";
voiceFor["pv-stridex-voicemail"]="TX3LPaxmHKxFdv7VOQHJ";downloadable.add("pv-stridex-voicemail");
let cachedVoiceId:string|null=null;async function getAvailableVoiceId(apiKey:string){if(cachedVoiceId)return cachedVoiceId;const response=await fetch("https://api.elevenlabs.io/v1/voices",{headers:{"xi-api-key":apiKey},cache:"no-store"});if(!response.ok)return null;const data=await response.json();const voices=Array.isArray(data.voices)?data.voices:[];const preferred=voices.find((voice:any)=>{const labels=voice.labels||{};return String(labels.gender||"").toLowerCase()==="female"&&(String(labels.accent||"").toLowerCase().includes("british")||String(labels.accent||"").toLowerCase().includes("english"))})||voices.find((voice:any)=>String((voice.labels||{}).gender||"").toLowerCase()==="female")||voices[0];cachedVoiceId=preferred?.voice_id||null;return cachedVoiceId}
export async function POST(request:Request){const apiKey=process.env.ELEVENLABS_API_KEY;if(!apiKey)return NextResponse.json({error:"ELEVENLABS_API_KEY is not configured."},{status:500});let body:{key?:string};try{body=await request.json()}catch{return NextResponse.json({error:"Invalid JSON body."},{status:400})}const text=body.key?scripts[body.key]:undefined;if(!text)return NextResponse.json({error:"Unknown audio key."},{status:400});const fixedVoice=voiceFor[body.key!]||"";return storedVoice(["tts",text,fixedVoice],async()=>{const voiceId=fixedVoice||await getAvailableVoiceId(apiKey);if(!voiceId)return NextResponse.json({error:"No ElevenLabs voice is available for this account."},{status:502});const response=await fetch(`https://api.elevenlabs.io/v1/text-to-speech/${voiceId}?output_format=mp3_44100_128`,{method:"POST",headers:{"xi-api-key":apiKey,"Content-Type":"application/json",Accept:"audio/mpeg"},body:JSON.stringify({text,model_id:"eleven_multilingual_v2",language_code:"en",voice_settings:{stability:.78,similarity_boost:.78,style:0,use_speaker_boost:true,speed:.9}})});if(!response.ok)return NextResponse.json({error:"Voice generation failed."},{status:502});const audio=await response.arrayBuffer();return new Response(audio,{status:200,headers:{"Content-Type":"audio/mpeg","Cache-Control":"no-store"}})});}
export async function GET(request:Request){const apiKey=process.env.ELEVENLABS_API_KEY;if(!apiKey)return NextResponse.json({error:"ELEVENLABS_API_KEY is not configured."},{status:500});const key=new URL(request.url).searchParams.get("key")||"";if(!downloadable.has(key))return NextResponse.json({error:"Unknown audio key."},{status:400});const stored=await storedVoice(["tts-download",scripts[key],voiceFor[key]],async()=>{const response=await fetch(`https://api.elevenlabs.io/v1/text-to-speech/${voiceFor[key]}?output_format=mp3_44100_128`,{method:"POST",headers:{"xi-api-key":apiKey,"Content-Type":"application/json",Accept:"audio/mpeg"},body:JSON.stringify({text:scripts[key],model_id:"eleven_multilingual_v2",language_code:"en",voice_settings:{stability:.6,similarity_boost:.8,style:.15,use_speaker_boost:true,speed:.92}})});if(!response.ok)return NextResponse.json({error:"Voice generation failed."},{status:502});const audio=await response.arrayBuffer();return new Response(audio,{status:200,headers:{"Content-Type":"audio/mpeg"}})});if(!stored.ok)return stored;return new Response(await stored.arrayBuffer(),{status:200,headers:{"Content-Type":"audio/mpeg","Content-Disposition":`attachment; filename="${key}.mp3"`,"Cache-Control":"public, max-age=86400","X-Voice-Source":stored.headers.get("X-Voice-Source")||""}})}
