"use client";
import {useEffect,useRef,useState} from "react";
import {useRouter} from "next/navigation";
import "../alphabet.css";

const customers=["CARTER","PHILLIPS","GOMEZ","HUGHES"];
const css=`.rl{max-width:1080px;margin:auto}.rlCard{padding:38px}.rlHead{display:flex;justify-content:space-between;gap:20px;align-items:flex-start}.rlHead h1{font-size:36px;margin:8px 0}.rlHead p{color:#b9c2e5;margin:0}.timer{min-width:120px;text-align:center;padding:14px;border:1px solid #5963b2;border-radius:16px;background:#101630;color:#cbd1ee}.timer b{display:block;font-size:30px;color:#fff}.scenario{max-width:760px;margin:28px auto;padding:22px;border:1px solid #424b91;border-radius:18px;background:#0c122c;color:#c8d0ed}.audioBox{max-width:760px;margin:20px auto;padding:28px;text-align:center;border:1px solid #5148a8;border-radius:24px;background:radial-gradient(circle at 50% 0,#252d65,#0d132e 68%)}.play{border:0;border-radius:17px;padding:17px 34px;color:white;font-size:18px;font-weight:900;background:linear-gradient(#765fff,#4934c9);box-shadow:0 7px 0 #2b1d7c;cursor:pointer}.play:disabled{opacity:.5}.fields{max-width:760px;margin:25px auto;display:grid;gap:13px}.row{display:grid;grid-template-columns:48px 1fr;align-items:center;gap:12px}.row span{font-weight:900;color:#aeb8df}.row input{box-sizing:border-box;width:100%;padding:16px 18px;border:1px solid #5963b2;border-radius:14px;background:#0b1128;color:#fff;font-size:20px;font-weight:800;letter-spacing:.07em;text-transform:uppercase;outline:none}.row input.good{border-color:#32c98a}.row input.bad{border-color:#ef6f87}.submit{display:block;width:100%;max-width:760px;margin:20px auto;padding:17px;border:0;border-radius:15px;color:#fff;font-size:17px;font-weight:900;background:linear-gradient(#3b8cff,#2256d4);box-shadow:0 7px 0 #15368e;cursor:pointer}.submit:disabled{opacity:.4}.feedback{max-width:760px;margin:18px auto;padding:17px;text-align:center;border:1px solid #343c76;border-radius:15px;background:#0a1025;color:#b8c1e5}.result{text-align:center;padding:55px}.result h1{font-size:42px}.stats{display:grid;grid-template-columns:repeat(3,1fr);gap:14px;max-width:650px;margin:28px auto}.stat{padding:20px;border:1px solid #465096;border-radius:17px;background:#101630}.stat b{display:block;font-size:30px}.stat small{color:#aeb8df}@media(max-width:650px){.rlCard{padding:20px}.rlHead{display:block}.timer{display:inline-block;margin-top:15px}.stats{grid-template-columns:1fr}}`;
const clean=(s:string)=>s.toUpperCase().replace(/[^A-Z]/g,"");
export default function RealLife(){const router=useRouter();const[started,setStarted]=useState(false),[seconds,setSeconds]=useState(90),[values,setValues]=useState(["","","",""]),[done,setDone]=useState(false),[busy,setBusy]=useState(false),[audioError,setAudioError]=useState("");const audio=useRef<HTMLAudioElement|null>(null);
useEffect(()=>{if(!started||done)return;const id=setInterval(()=>setSeconds(s=>{if(s<=1){clearInterval(id);setDone(true);return 0}return s-1}),1000);return()=>clearInterval(id)},[started,done]);
async function play(){if(busy)return;setStarted(true);setBusy(true);setAudioError("");try{const r=await fetch('/api/tts',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({key:'real-life-message'}),cache:'no-store'});if(!r.ok)throw new Error('Voice generation failed.');const blob=await r.blob();const url=URL.createObjectURL(blob);const a=new Audio(url);audio.current=a;a.onended=()=>{setBusy(false);URL.revokeObjectURL(url)};a.onerror=()=>{setBusy(false);setAudioError('The message could not be played.');URL.revokeObjectURL(url)};await a.play()}catch(e:any){setBusy(false);setAudioError(e.message||'Audio error')}}
const score=customers.filter((x,n)=>clean(values[n])===x).length;function submit(){if(!started)return;audio.current?.pause();setDone(true)}const mm=String(Math.floor(seconds/60)).padStart(2,'0'),ss=String(seconds%60).padStart(2,'0');
if(done){const pct=Math.round(score/customers.length*100);return <main className="alphabet-page"><style>{css}</style><div className="rl"><div className="alphabet-topbar"><div className="lesson-pill">STEP 7 / 10 · REAL-LIFE CHALLENGE</div><button className="exit-btn" onClick={()=>router.push('/alphabet')}>EXIT</button></div><section className="panel result"><span className="eyebrow">PROFESSIONAL MESSAGE COMPLETE</span><h1>{pct}% ACCURACY</h1><p>You captured {score} of {customers.length} customer names correctly.</p><div className="stats"><div className="stat"><b>{score}/4</b><small>CORRECT</small></div><div className="stat"><b>{4-score}</b><small>ERRORS</small></div><div className="stat"><b>{mm}:{ss}</b><small>TIME LEFT</small></div></div><div className="fields">{customers.map((x,n)=><div className="row" key={x}><span>{n+1}</span><input readOnly className={clean(values[n])===x?'good':'bad'} value={values[n]||'—'}/></div>)}</div><div className="identify-actions"><button className="nav3d" onClick={()=>{setStarted(false);setSeconds(90);setValues(["","","",""]);setDone(false);setAudioError("")}}>↻ TRY AGAIN</button><button className="nav3d next" onClick={()=>router.push('/alphabet/results')}>SEE RESULTS ›</button></div></section></div></main>}
return <main className="alphabet-page"><style>{css}</style><div className="rl"><div className="alphabet-topbar"><div className="lesson-pill">STEP 7 / 10 · REAL-LIFE CHALLENGE</div><button className="exit-btn" onClick={()=>router.push('/alphabet')}>EXIT</button></div><section className="panel rlCard"><div className="rlHead"><div><span className="eyebrow">CADGA · CUSTOMER SERVICE SCENARIO</span><h1>TAKE THE MESSAGE.</h1><p>Listen to a professional customer-service message and type the four customer names you hear.</p></div><div className="timer">TIME<b>{mm}:{ss}</b></div></div><div className="scenario"><b>SCENARIO</b><br/>You are handling customer information. A colleague leaves you a message containing four customer names, spelled out for accuracy. Record them in the same order.</div><div className="audioBox"><button className="play" onClick={play} disabled={busy}>🔊 {busy?'PLAYING MESSAGE…':started?'LISTEN AGAIN':'START & LISTEN'}</button>{audioError&&<p style={{color:'#ffb3c0'}}>{audioError}</p>}<p style={{color:'#aeb8df'}}>The 90-second timer starts when you play the message.</p></div><div className="fields">{values.map((v,n)=><div className="row" key={n}><span>{n+1}.</span><input value={v} onChange={e=>setValues(a=>a.map((x,j)=>j===n?e.target.value:x))} placeholder="CUSTOMER NAME" autoComplete="off"/></div>)}</div><button className="submit" onClick={submit} disabled={!started||values.some(v=>!v.trim())}>SUBMIT MESSAGE</button><div className="feedback">Listen carefully. Names must be entered in the order you hear them.</div><button className="nav3d" onClick={()=>router.push('/alphabet/listen-type')}>‹ STEP 6</button></section></div></main>}
