"use client";
import {createSpeechRecognition,speechErrorMessage} from "@/lib/speech-recognition";

import {useEffect,useMemo,useRef,useState} from "react";
import {useRouter} from "next/navigation";
import "./time.css";
import {SummaryCard} from "@/app/ModuleSummary";

type TimeItem={written:string;spoken:string};

const hours:TimeItem[]=Array.from({length:12},(_,index)=>({written:`${index+1}:00`,spoken:`${["one","two","three","four","five","six","seven","eight","nine","ten","eleven","twelve"][index]} o'clock`}));
const minutes:TimeItem[]=[
 {written:"7:05",spoken:"seven oh five"},{written:"7:10",spoken:"seven ten"},{written:"7:20",spoken:"seven twenty"},{written:"7:25",spoken:"seven twenty-five"},
 {written:"7:35",spoken:"seven thirty-five"},{written:"7:40",spoken:"seven forty"},{written:"7:50",spoken:"seven fifty"},{written:"7:55",spoken:"seven fifty-five"},
];
const british:TimeItem[]=[
 {written:"7:00",spoken:"seven o'clock"},{written:"7:05",spoken:"five past seven"},{written:"7:15",spoken:"quarter past seven"},{written:"7:30",spoken:"half past seven"},
 {written:"7:40",spoken:"twenty to eight"},{written:"7:45",spoken:"quarter to eight"},{written:"7:50",spoken:"ten to eight"},{written:"7:55",spoken:"five to eight"},
];
const quiz=[
 {spoken:"quarter past nine",answer:"09:15",options:["09:15","09:45","08:15"]},{spoken:"twenty past eleven",answer:"11:20",options:["11:20","11:40","10:20"]},
 {spoken:"half past two",answer:"14:30",options:["14:13","14:30","15:30"]},{spoken:"quarter to five",answer:"16:45",options:["17:15","16:45","16:15"]},
 {spoken:"ten to eight",answer:"19:50",options:["19:10","20:10","19:50"]},{spoken:"six oh five",answer:"06:05",options:["06:50","06:05","05:06"]},
 {spoken:"twenty-five to one",answer:"12:35",options:["12:25","13:35","12:35"]},{spoken:"nine o'clock",answer:"09:00",options:["09:00","19:00","09:30"]},
];
const sayTimes:TimeItem[]=[
 {written:"08:15",spoken:"quarter past eight"},{written:"09:30",spoken:"half past nine"},{written:"10:45",spoken:"quarter to eleven"},{written:"11:20",spoken:"twenty past eleven"},
 {written:"14:35",spoken:"twenty-five to three"},{written:"16:50",spoken:"ten to five"},{written:"18:05",spoken:"five past six"},{written:"21:00",spoken:"nine o'clock"},
];
const challenges=[
 {title:"Training start",message:"Good morning. Today's CADGA training session starts at quarter past eight.",answer:"08:15"},
 {title:"Team briefing",message:"The customer service team briefing is scheduled for half past nine.",answer:"09:30"},
 {title:"Registration deadline",message:"Please send the completed registration form by quarter to eleven.",answer:"10:45"},
 {title:"Candidate call",message:"Your telephone interview with the candidate begins at twenty past eleven.",answer:"11:20"},
 {title:"Afternoon assessment",message:"The practical assessment will start at twenty-five to three this afternoon.",answer:"14:35"},
 {title:"Customer appointment",message:"The customer appointment has been moved to ten to five.",answer:"16:50"},
 {title:"Results call",message:"Please call the candidate with the results at five past six.",answer:"18:05"},
 {title:"Online meeting",message:"The final online meeting begins at nine o'clock this evening.",answer:"21:00"},
];
const steps=["Welcome","Hours & O'Clock","Minutes","Past, To & Quarters","Listen & Identify","Say the Time","Real-Life Challenge","Results & Remediation","Validation"];
const descriptions=["Start the module","Repeat hours from one to twelve","Practise precise digital times","Use British time expressions","Choose the time you hear","Pronounce eight displayed times","Take notes from eight messages","Review your performance","Complete the final check"];

async function speak(text:string){const response=await fetch("/api/symbol-tts",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({text,speed:.86})});if(!response.ok)throw new Error("Natural voice unavailable");const url=URL.createObjectURL(await response.blob()),audio=new Audio(url);audio.onended=()=>URL.revokeObjectURL(url);audio.onerror=()=>URL.revokeObjectURL(url);await audio.play()}
const speechNumbers:[string,string][]=[["twenty five","25"],["twenty four","24"],["twenty three","23"],["twenty two","22"],["twenty one","21"],["twenty","20"],["nineteen","19"],["eighteen","18"],["seventeen","17"],["sixteen","16"],["fifteen","15"],["fourteen","14"],["thirteen","13"],["twelve","12"],["eleven","11"],["ten","10"],["nine","9"],["eight","8"],["seven","7"],["six","6"],["five","5"],["four","4"],["three","3"],["two","2"],["one","1"],["oh","0"]];
function normalize(value:string){let result=value.toLowerCase().replace(/[’']/g,"").replace(/-/g," ").replace(/o\s*clock/g,"oclock");for(const [word,number] of speechNumbers)result=result.replace(new RegExp(`\\b${word}\\b`,"g"),number);return result.replace(/[^a-z0-9]/g,"")}
function Clock({value}:{value:string}){const [hourText,minuteText]=value.split(":"),hour=Number(hourText)%12,minute=Number(minuteText),minuteAngle=minute*6,hourAngle=hour*30+minute/2;return <svg className="time-clock" viewBox="0 0 200 200" role="img" aria-label={value}><circle cx="100" cy="100" r="91"/><g className="ticks">{Array.from({length:12},(_,index)=><line key={index} x1="100" y1="18" x2="100" y2="28" transform={`rotate(${index*30} 100 100)`}/>)}</g><line className="hour-hand" x1="100" y1="100" x2="100" y2="54" transform={`rotate(${hourAngle} 100 100)`}/><line className="minute-hand" x1="100" y1="100" x2="100" y2="31" transform={`rotate(${minuteAngle} 100 100)`}/><circle className="pin" cx="100" cy="100" r="7"/></svg>}

export default function TimeModule(){
 const router=useRouter(),recognition=useRef<any>(null);
 const [step,setStep]=useState(1),[entered,setEntered]=useState(false),[hourIndex,setHourIndex]=useState(0),[minuteIndex,setMinuteIndex]=useState(0),[britishIndex,setBritishIndex]=useState(0),[quizIndex,setQuizIndex]=useState(0),[choice,setChoice]=useState(""),[score,setScore]=useState(0),[sayIndex,setSayIndex]=useState(0),[challengeIndex,setChallengeIndex]=useState(0),[notes,setNotes]=useState(Array(8).fill("")),[challengePlayed,setChallengePlayed]=useState(Array(8).fill(false)),[heard,setHeard]=useState(""),[expected,setExpected]=useState(""),[listening,setListening]=useState(false),[attempts,setAttempts]=useState(0),[audioError,setAudioError]=useState(""),[finalIndex,setFinalIndex]=useState(0),[finalScore,setFinalScore]=useState(0);
 const finalQuestions=useMemo(()=>[quiz[1],quiz[4],quiz[6]],[]),speechOk=!!heard&&normalize(heard)===normalize(expected);
 useEffect(()=>setEntered(true),[]);
 function go(value:number){setStep(Math.max(1,Math.min(9,value)));setHeard("");setExpected("");setAudioError("");window.scrollTo({top:0,behavior:"smooth"})}
 function record(target:string){const instance=createSpeechRecognition();if(!instance){setHeard(speechErrorMessage("unsupported"));return}setExpected(target);setHeard("");setListening(true);recognition.current=instance;instance.lang="en-GB";instance.interimResults=false;instance.continuous=false;instance.onresult=(event:any)=>{setHeard(event.results[0][0].transcript);setAttempts(value=>value+1);setListening(false)};instance.onerror=(event)=>{setHeard(speechErrorMessage(event?.error));setListening(false)};instance.onend=()=>setListening(false);instance.start()}
 async function play(text:string){setAudioError("");try{await speak(text)}catch{setAudioError("The natural voice could not be played. Please try again.")}}
 function answerQuiz(value:string){if(choice)return;setChoice(value);if(value===quiz[quizIndex].answer)setScore(current=>current+1)}
 function nextQuiz(){if(quizIndex<7){setQuizIndex(index=>index+1);setChoice("")}else go(6)}
 function setNote(value:string){setNotes(current=>current.map((note,index)=>index===challengeIndex?value:note))}
 function playChallenge(){setChallengePlayed(current=>current.map((played,index)=>index===challengeIndex?true:played));play(challenges[challengeIndex].message)}
 function activityIndex(){return step===2?hourIndex:step===3?minuteIndex:step===4?britishIndex:step===5?quizIndex:step===6?sayIndex:step===7?challengeIndex:-1}
 function activityTotal(){return step===2?hours.length:step>=3&&step<=7?8:0}
 function setActivity(index:number){if(step===2)setHourIndex(index);if(step===3)setMinuteIndex(index);if(step===4)setBritishIndex(index);if(step===5){setQuizIndex(index);setChoice("")}if(step===6)setSayIndex(index);if(step===7){setChallengeIndex(index);setAudioError("")}setHeard("");setExpected("")}
 function footerPrevious(){const index=activityIndex();if(index>0){setActivity(index-1);return}go(step-1)}
 function footerNext(){const index=activityIndex(),total=activityTotal();if(index>=0&&index<total-1){setActivity(index+1);return}go(step+1)}
 function finalAnswer(value:string){if(value===finalQuestions[finalIndex].answer)setFinalScore(current=>current+1);setFinalIndex(index=>index+1)}
 const repeatItem=step===2?hours[hourIndex]:step===3?minutes[minuteIndex]:british[britishIndex],index=activityIndex(),total=activityTotal();
 return <main className="time-page"><div className="time-shell"><header className="time-top"><div><span>CADGA · MODULE 05</span><strong>TIME &amp; TELLING THE TIME</strong></div><div className="time-progress"><i><em style={{width:`${step/9*100}%`}}/></i><small>STEP {step} / 9</small></div><button onClick={()=>router.push("/welcome?overview=1")}>EXIT</button></header>
 {step===1&&<div style={{"--accent":"#ffbd64","--accent-dark":"#c46d22","--surface":"#4a2d20"} as any}><SummaryCard title="TIME & TELLING THE TIME" description="Choose any step below. Listen to the natural British voice and practise professional time expressions." steps={steps.slice(1).map((title,itemIndex)=>({title,description:descriptions[itemIndex+1]}))} onSelect={itemIndex=>go(itemIndex+2)}/></div>} 
 {step>=2&&step<=4&&<section className="time-card learn-time"><div className="lesson-heading"><span>{step===2?"LISTEN · REPEAT · REMEMBER":step===3?"PRECISE TIMES":"BRITISH ENGLISH"}</span><h1>{steps[step-1]}</h1><p>{step===2?"Select an hour, listen to the natural voice, then repeat it aloud.":step===3?"Practise minutes and precise digital times.":"Learn the CADGA way: past, to, quarter past, half past and quarter to."}</p></div><div className="time-focus"><Clock value={repeatItem.written}/><div><small>SELECTED TIME</small><strong>{repeatItem.written}</strong><p>{repeatItem.spoken}</p><div className="listen-repeat"><button onClick={()=>play(repeatItem.spoken)}>🔊 LISTEN</button><button onClick={()=>record(repeatItem.spoken)}>🎙 REPEAT</button></div>{heard&&expected===repeatItem.spoken&&<div className={speechOk?"time-transcript good":"time-transcript"}><small>I HEARD</small><b>“{heard}”</b><span>{speechOk?"✓ Correct — pronunciation validated.":"Listen again, then repeat the complete time."}</span></div>}</div></div><div className="time-choice-grid">{(step===2?hours:step===3?minutes:british).map((item,itemIndex)=><button className={(step===2?hourIndex:step===3?minuteIndex:britishIndex)===itemIndex?"active":""} key={item.written+item.spoken} onClick={()=>{step===2?setHourIndex(itemIndex):step===3?setMinuteIndex(itemIndex):setBritishIndex(itemIndex);setHeard("");setExpected("")}}><b>{item.written}</b><span>{item.spoken}</span></button>)}</div></section>}
 {step===5&&<section className="time-card time-quiz"><div className="quiz-heading"><span>LISTEN &amp; IDENTIFY · 8 AUDIO QUESTIONS</span><h1>Which time did you hear?</h1><b>{quizIndex+1} / 8</b></div><div className="number-tabs">{quiz.map((_,itemIndex)=><button className={quizIndex===itemIndex?"active":""} key={itemIndex} onClick={()=>{setQuizIndex(itemIndex);setChoice("")}}>{itemIndex+1}</button>)}</div><button className="audio-orb" onClick={()=>play(quiz[quizIndex].spoken)}>🔊<span>PLAY AUDIO {quizIndex+1}</span></button><div className="time-options">{quiz[quizIndex].options.map(value=><button className={choice?value===quiz[quizIndex].answer?"correct":value===choice?"wrong":"":""} key={value} onClick={()=>answerQuiz(value)}><Clock value={value}/><b>{value}</b></button>)}</div>{choice&&<div className="time-feedback">{choice===quiz[quizIndex].answer?"✓ Correct — well done!":"Not quite. Listen again and compare the hour and minutes."}<button onClick={nextQuiz}>{quizIndex===7?"CONTINUE":"NEXT TIME"} →</button></div>}</section>}
 {step===6&&<section className="time-card say-time"><span>SAY THE TIME · 8 TIMES TO COMPLETE</span><h1>{sayTimes[sayIndex].written}</h1><Clock value={sayTimes[sayIndex].written}/><p>Only the numeric time is shown. Listen to the model if needed, then repeat it.</p><div className="listen-repeat large"><button onClick={()=>play(sayTimes[sayIndex].spoken)}>🔊 LISTEN</button><button className={listening?"listening":""} onClick={()=>record(sayTimes[sayIndex].spoken)}>🎙 {listening?"LISTENING…":"REPEAT"}</button></div>{heard&&expected===sayTimes[sayIndex].spoken&&<div className={speechOk?"time-transcript good":"time-transcript"}><small>I HEARD</small><b>“{heard}”</b><span>{speechOk?"✓ Complete time validated.":"Listen to the model, then repeat the complete time."}</span></div>}<div className="say-time-grid">{sayTimes.map((item,itemIndex)=><button className={sayIndex===itemIndex?"active":""} key={item.written} onClick={()=>{setSayIndex(itemIndex);setHeard("");setExpected("")}}><small>{itemIndex+1}</small>{item.written}</button>)}</div></section>}
 {step===7&&<section className="time-card challenge-time"><div><span>REAL-LIFE CHALLENGE · MESSAGE {challengeIndex+1} / 8</span><h1>{challenges[challengeIndex].title}</h1><p>Listen to the professional message and write only the important time.</p><div className="number-tabs">{challenges.map((_,itemIndex)=><button className={challengeIndex===itemIndex?"active":""} key={itemIndex} onClick={()=>{setChallengeIndex(itemIndex);setAudioError("")}}>{itemIndex+1}</button>)}</div><button className="time-primary" onClick={playChallenge}>🔊 {challengePlayed[challengeIndex]?"PLAY AGAIN":"PLAY MESSAGE"}</button>{audioError&&<p className="audio-error">{audioError}</p>}</div><label>YOUR NOTE<textarea value={notes[challengeIndex]} onChange={event=>setNote(event.target.value)} placeholder="Write the time here…"/>{challengePlayed[challengeIndex]&&notes[challengeIndex].trim()&&<details><summary>CHECK THE CORRECTION</summary><p>The important time is <b>{challenges[challengeIndex].answer}</b>.</p></details>}</label></section>}
 {step===8&&<section className="time-card time-results"><span>RESULTS &amp; REMEDIATION</span><h1>Your time profile</h1><div className="time-score" style={{background:`conic-gradient(#ffad42 ${score/8*360}deg,#421d20 0)`}}><b>{Math.round(score/8*100)}%</b></div><div className="result-grid"><div><b>{score}/8</b><span>LISTENING</span></div><div><b>{attempts}</b><span>SPEAKING ATTEMPTS</span></div><div><b>{challengePlayed.filter(Boolean).length}/8</b><span>REAL-LIFE MESSAGES</span></div></div><p>{score<6?"Review Listen & Identify to strengthen time recognition before validation.":"Excellent. You are ready for the final validation."}</p><button className="time-secondary" onClick={()=>go(score<6?5:9)}>{score<6?"REVIEW LISTENING":"START VALIDATION"} →</button></section>}
 {step===9&&<section className="time-card time-validation">{finalIndex<3?<><span>FINAL VALIDATION · QUESTION {finalIndex+1} / 3</span><h1>Listen and choose.</h1><button className="audio-orb" onClick={()=>play(finalQuestions[finalIndex].spoken)}>🔊<span>PLAY AUDIO</span></button><div className="time-options compact">{finalQuestions[finalIndex].options.map(value=><button key={value} onClick={()=>finalAnswer(value)}><Clock value={value}/><b>{value}</b></button>)}</div></>:<><div className="time-award">★</div><span>MODULE 05 COMPLETE</span><h1>{finalScore>=2?"ACQUIRED":"KEEP PRACTISING"}</h1><p>You scored {finalScore}/3. {finalScore>=2?"You can understand and give the time in a professional context.":"Review the listening activities, then try again."}</p><button className="time-primary" onClick={()=>router.push("/welcome?overview=1")}>BACK TO MY JOURNEY</button></>}</section>}
 {audioError&&step!==7&&<div className="global-audio-error">{audioError}</div>}
 {step>1&&step<9&&<footer className="time-footer"><button onClick={footerPrevious}>‹ {index>0?"PREVIOUS TIME":"PREVIOUS"}</button><span>{steps[step-1].toUpperCase()}{index>=0&&` · ${index+1} / ${total}`}</span><button className="time-primary" onClick={footerNext}>{index>=0&&index<total-1?"NEXT TIME →":"NEXT STEP →"}</button></footer>}
 </div></main>
}
