"use client";

import {useEffect,useMemo,useRef,useState} from "react";
import Image from "next/image";
import Link from "next/link";
import "./ecf.css";

type Key="firstName"|"lastName"|"job"|"company"|"city"|"country"|"reason"|"services"|"request"|"countryCode"|"phone"|"email";
type Criterion={title:string;acquired:boolean;observation:string;remedy:string;question:string};
const labels:Record<Key,string>={firstName:"Prénom",lastName:"Nom",job:"Fonction",company:"Entreprise",city:"Ville",country:"Pays",reason:"Motif de l’appel",services:"Domaines d’intérêt",request:"Demande et action attendue",countryCode:"Indicatif international",phone:"Numéro de téléphone",email:"Adresse email"};
const expected:Record<Key,string>={firstName:"Anna",lastName:"Schneider",job:"Directrice des opérations",company:"TechPro Systems",city:"Munich",country:"Allemagne",reason:"Entreprise en forte croissance recherchant un partenaire fiable",services:"Solutions numériques, gestion de projet, formation et développement, recrutement en ressources humaines",request:"Recevoir une présentation de l’entreprise, la liste détaillée des services et les tarifs ; organiser une réunion en ligne ; être rappelée rapidement par Julien Lambert",countryCode:"+49",phone:"89 1234 5678",email:"anna.schneider@techpro-systems.de"};
const keys=Object.keys(labels) as Key[];
const norm=(v:string)=>v.toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/[^a-z0-9@+]+/g," ").trim();
const digits=(v:string)=>v.replace(/\D/g,"");
const has=(v:string,terms:string[])=>terms.every(t=>norm(v).includes(norm(t)));
function correct(k:Key,v:string){if(!v.trim())return false;if(k==="firstName")return norm(v)==="anna";if(k==="lastName")return norm(v)==="schneider";if(k==="job")return has(v,["directrice","operations"])||has(v,["directeur","operations"]);if(k==="company")return has(v,["techpro","systems"]);if(k==="city")return norm(v).includes("munich");if(k==="country")return norm(v).includes("allemagne");if(k==="countryCode")return digits(v)==="49";if(k==="phone")return ["8912345678","08912345678"].includes(digits(v));if(k==="email")return v.toLowerCase().replace(/\s/g,"")===expected.email;if(k==="reason")return has(v,["croissance","partenaire"])||has(v,["developpe","partenaire"]);if(k==="services")return [["numeriques","projet","formation","recrutement"],["digitales","projet","formation","ressources humaines"]].some(g=>has(v,g));return has(v,["presentation","services","tarifs"])&&(norm(v).includes("reunion")||norm(v).includes("entretien"))&&(norm(v).includes("rappel")||norm(v).includes("contacter"));}

export default function EcfPartOne(){
 const [stage,setStage]=useState(0);const [part,setPart]=useState<1|2>(1);const [startedAt,setStartedAt]=useState<number|null>(null);const [now,setNow]=useState(Date.now());const [submittedAt,setSubmittedAt]=useState<number|null>(null);const [form,setForm]=useState<Record<Key,string>>(Object.fromEntries(keys.map(k=>[k,""])) as Record<Key,string>);const [recipient,setRecipient]=useState("");const [subject,setSubject]=useState("");const [message,setMessage]=useState("");const audio=useRef<HTMLAudioElement>(null);
 useEffect(()=>{if(!startedAt||submittedAt)return;const id=window.setInterval(()=>setNow(Date.now()),1000);return()=>window.clearInterval(id)},[startedAt,submittedAt]);
 const elapsed=startedAt?Math.floor(((submittedAt??now)-startedAt)/1000):0;const remaining=Math.max(0,1800-elapsed);const mm=String(Math.floor(remaining/60)).padStart(2,"0"),ss=String(remaining%60).padStart(2,"0");
 const results=useMemo(()=>Object.fromEntries(keys.map(k=>[k,correct(k,form[k])])) as Record<Key,boolean>,[form]);
 const criteria=useMemo<Criterion[]>(()=>{const body=norm(message),rec=norm(recipient),sub=norm(subject);const identity=results.firstName&&results.lastName;const context=results.job&&results.company&&results.city&&results.country;const motive=results.reason;const services=results.services;const action=results.request;const contact=results.countryCode&&results.phone&&results.email;const recipientOk=rec.includes("julien")&&rec.includes("lambert");const subjectOk=["prospect","demande","information","partenariat","collaboration"].some(x=>sub.includes(x));const faithful=has(message,["anna","schneider","techpro"])&&(body.includes("services")||body.includes("solutions"))&&(body.includes("tarif")||body.includes("prix"))&&(body.includes("reunion")||body.includes("entretien"));const professional=message.trim().length>=180&&(body.includes("bonjour")||body.includes("monsieur"))&&(body.includes("cordialement")||body.includes("bien cordialement"));return [
 {title:"Identifier précisément l’interlocutrice",acquired:identity,observation:identity?"Le prénom et le nom sont exacts.":"Le prénom ou le nom comporte une erreur.",remedy:"Reprendre l’épellation et comparer uniquement les lettres qui diffèrent.",question:"Comment as-tu procédé pour identifier puis vérifier le prénom et le nom ?"},
 {title:"Relever le contexte professionnel",acquired:context,observation:context?"La fonction, l’entreprise et la localisation sont complètes.":"Une information de contexte manque ou n’est pas formulée en français.",remedy:"Réécouter les expressions qui introduisent la fonction, l’entreprise et la localisation.",question:"Quels mots t’ont permis de distinguer la fonction, l’entreprise, la ville et le pays ?"},
 {title:"Comprendre le motif de l’appel",acquired:motive,observation:motive?"La situation de l’entreprise et la recherche d’un partenaire sont comprises.":"La croissance de l’entreprise ou la recherche d’un partenaire fiable n’apparaît pas clairement.",remedy:"Distinguer le contexte de l’appel de la liste des demandes formulées.",question:"À quel moment as-tu compris pourquoi la personne appelait ?"},
 {title:"Identifier les domaines d’intérêt",acquired:services,observation:services?"Les quatre domaines sont restitués.":"Un ou plusieurs domaines d’intérêt sont absents.",remedy:"Réécouter l’énumération et noter un mot-clé par domaine.",question:"Comment as-tu mémorisé et organisé l’énumération des quatre domaines ?"},
 {title:"Identifier la demande et les actions attendues",acquired:action,observation:action?"Les documents, la réunion et le rappel sont identifiés.":"Une demande ou une action attendue manque.",remedy:"Séparer les documents à envoyer, la réunion à organiser et la personne qui doit rappeler.",question:"Comment as-tu distingué les documents demandés des actions à réaliser ?"},
 {title:"Relever exactement les coordonnées",acquired:contact,observation:contact?"L’indicatif, le numéro et l’adresse email sont exacts.":"Une coordonnée comporte une omission, une inversion ou une confusion.",remedy:"Réécouter les coordonnées groupe par groupe et caractère par caractère.",question:"Quelle stratégie as-tu utilisée pour vérifier le numéro et l’adresse email ?"},
 {title:"Choisir le bon destinataire",acquired:recipientOk,observation:recipientOk?"Le message est adressé au dirigeant concerné.":"Le destinataire choisi ne correspond pas à l’action demandée.",remedy:"Croiser la fonction citée dans le message avec l’organigramme.",question:"Qu’as-tu recherché dans l’organigramme avant de choisir le destinataire ?"},
 {title:"Rédiger un objet clair",acquired:subjectOk,observation:subjectOk?"L’objet annonce clairement la nature de la demande.":"L’objet reste trop vague ou ne permet pas de prioriser le message.",remedy:"Faire apparaître le prospect et l’objet principal de son appel.",question:"Comment as-tu choisi les mots à faire apparaître dans l’objet ?"},
 {title:"Transmettre fidèlement les informations essentielles",acquired:faithful,observation:faithful?"L’identité, les services, les tarifs et la réunion sont transmis.":"Une information essentielle n’est pas exploitable dans l’email.",remedy:"Comparer l’email avec la fiche et cocher chaque information transmise.",question:"Comment as-tu sélectionné les informations à conserver dans l’email ?"},
 {title:"Produire un email professionnel dans le temps imparti",acquired:professional&&elapsed<=1800,observation:professional?(elapsed<=1800?"Le message est structuré et produit dans les 30 minutes.":"Le message est structuré mais le temps est dépassé."):"La structure ou le ton professionnel doit être renforcé.",remedy:"Utiliser une trame courte : destinataire, contexte, demande, actions, coordonnées et clôture.",question:"Comment as-tu organisé ton temps entre l’écoute, la vérification et la rédaction ?"}
 ]},[results,recipient,subject,message,elapsed]);
 const acquired=criteria.filter(c=>c.acquired).length;const essential=criteria[4].acquired&&criteria[5].acquired&&criteria[6].acquired&&criteria[8].acquired;const verdict=acquired>=8&&essential?"ACQUIS":"NON ACQUIS";const failed=criteria.filter(c=>!c.acquired);
 const begin=()=>{setStartedAt(Date.now());setNow(Date.now());setStage(2)};const submit=()=>{setSubmittedAt(Date.now());setStage(3);window.scrollTo({top:0,behavior:"smooth"})};
 return <main className="ecf-page"><header className="ecf-top"><div><span>DAY 06 · ECF PART 1</span><strong>MISE EN SITUATION PROFESSIONNELLE</strong></div><div className="ecf-stages">{["Préparation","Consignes","Épreuve","Correction","Remédiation"].map((x,i)=><span className={stage===i?"active":stage>i?"done":""} key={x}><b>{i+1}</b>{x}</span>)}</div><Link href="/day4">EXIT</Link></header>
 <section className="ecf-shell">
 {stage===0&&<div className="ecf-calm"><div className="ecf-calm-copy"><span>AVANT L’ÉPREUVE</span><h1>Retrouver ses repères.</h1><p>Ce moment n’est pas évalué. Il permet simplement de se recentrer sur une méthode déjà travaillée.</p><div className="ecf-breathe"><i/><div><strong>Inspirer. Expirer.</strong><small>Prendre le temps de lire avant d’agir.</small></div></div></div><div className="ecf-checks"><article><b>01</b><div><h3>Anticiper</h3><p>Prendre connaissance de la fiche et des ressources.</p></div></article><article><b>02</b><div><h3>Écouter</h3><p>Repérer l’identité, le contexte, la demande et les coordonnées.</p></div></article><article><b>03</b><div><h3>Renseigner</h3><p>Compléter la fiche en français.</p></div></article><article><b>04</b><div><h3>Transmettre</h3><p>Choisir le destinataire puis rédiger un email exploitable.</p></div></article><button onClick={()=>setStage(1)}>JE SUIS PRÊT·E <b>→</b></button></div></div>}
 {stage===1&&<div className="ecf-instructions"><div className="ecf-heading"><span>CONSIGNES</span><h1>Deux productions · 30 minutes</h1><p>La correction et les réponses attendues resteront masquées jusqu’à la soumission définitive.</p></div><div className="ecf-parts"><article><b>15 MIN</b><h2>Partie 1 · Écouter</h2><p>Écouter le message et compléter la fiche de renseignements en français.</p></article><article><b>15 MIN</b><h2>Partie 2 · Transmettre</h2><p>Consulter les ressources, identifier le bon destinataire et rédiger l’email professionnel.</p></article></div><div className="ecf-rules"><span>Une seule soumission</span><span>Chronomètre global</span><span>Ressources accessibles</span></div><button className="ecf-primary" onClick={begin}>COMMENCER L’ECF <b>→</b></button></div>}
 {stage===2&&<div className="ecf-exam"><div className="ecf-exam-bar"><div><span>ÉPREUVE EN COURS</span><strong>PARTIE {part} / 2</strong></div><time className={remaining<300?"urgent":""}>{mm}:{ss}</time><div><button className={part===1?"active":""} onClick={()=>setPart(1)}>1 · FICHE</button><button className={part===2?"active":""} onClick={()=>setPart(2)}>2 · EMAIL</button></div></div>
 {part===1&&<div><div className="ecf-audio"><div><span>MESSAGE VOCAL</span><p>Écouter attentivement et compléter tous les champs.</p></div><audio ref={audio} controls preload="metadata" src="/day4/ecf-voicemail.m4a"/></div><div className="ecf-form">{keys.map(k=><label className={k==="reason"||k==="services"||k==="request"?"wide":""} key={k}><span>{labels[k]}</span>{k==="reason"||k==="services"||k==="request"?<textarea value={form[k]} onChange={e=>setForm({...form,[k]:e.target.value})}/>:<input value={form[k]} onChange={e=>setForm({...form,[k]:e.target.value})}/>}</label>)}</div><button className="ecf-primary next" onClick={()=>{setPart(2);window.scrollTo({top:0,behavior:"smooth"})}}>PASSER À LA PARTIE 2 →</button></div>}
 {part===2&&<div><div className="ecf-resources"><article><Image src="/day4/company-overview.jpg" alt="Infographie de l’entreprise" width={773} height={1095}/><div><strong>Infographie de l’entreprise</strong><a href="/day4/company-overview.pdf" target="_blank">CONSULTER LE DOCUMENT ↗</a></div></article><article><Image src="/day4/company-chart.jpg" alt="Organigramme de l’entreprise" width={773} height={1095}/><div><strong>Organigramme de l’entreprise</strong><a href="/day4/company-chart.pdf" target="_blank">CONSULTER LE DOCUMENT ↗</a></div></article></div><div className="ecf-mail"><label><span>À</span><input value={recipient} onChange={e=>setRecipient(e.target.value)} placeholder="Nom et fonction du destinataire"/></label><label><span>Objet</span><input value={subject} onChange={e=>setSubject(e.target.value)} placeholder="Objet clair et professionnel"/></label><textarea value={message} onChange={e=>setMessage(e.target.value)} placeholder={"Bonjour,\n\n..."}/></div><button className="ecf-submit" disabled={!recipient.trim()||!subject.trim()||message.trim().length<100} onClick={submit}>SOUMETTRE DÉFINITIVEMENT</button></div>}</div>}
 {stage===3&&<div className="ecf-correction"><div className="ecf-heading"><span>CORRECTION CRITÉRIÉE</span><h1>{acquired}/10 critères acquis</h1><p>Chaque résultat s’appuie sur un élément observable de la fiche ou de l’email.</p></div><div className="ecf-grid">{criteria.map((c,i)=><article className={c.acquired?"ok":"ko"} key={c.title}><b>{String(i+1).padStart(2,"0")}</b><div><h3>{c.title}</h3><p>{c.observation}</p>{!c.acquired&&<small>{c.remedy}</small>}</div><strong>{c.acquired?"ACQUIS":"NON ACQUIS"}</strong></article>)}</div><div className={`ecf-verdict ${verdict==="ACQUIS"?"ok":"ko"}`}><span>RÉSULTAT GLOBAL</span><h2>{verdict}</h2><p>{verdict==="ACQUIS"?"Les informations essentielles sont comprises et transmises de façon exploitable.":"Les difficultés observées vont maintenant servir à préparer une remédiation ciblée avec la formatrice."}</p></div><button className="ecf-primary" onClick={()=>{setStage(4);window.scrollTo({top:0,behavior:"smooth"})}}>PRÉPARER LA REMÉDIATION →</button></div>}
 {stage===4&&<div className="ecf-remediation"><div className="ecf-heading"><span>ESPACE REMÉDIATION</span><h1>Préparer l’entretien avec la formatrice</h1><p>Le diagnostic distingue les erreurs observées des causes qui devront être explorées pendant la visio.</p></div><div className="ecf-remed-layout"><section><h2>Synthèse transmise à la formatrice</h2><div className="ecf-summary"><div><span>Résultat</span><strong>{verdict}</strong></div><div><span>Critères acquis</span><strong>{acquired}/10</strong></div><div><span>Temps utilisé</span><strong>{Math.floor(elapsed/60)} min {elapsed%60} s</strong></div></div><h3>Difficultés observées</h3>{failed.length?failed.map(c=><article key={c.title}><strong>{c.title}</strong><p>{c.observation}</p><small>Remédiation proposée : {c.remedy}</small></article>):<p className="ecf-success">Aucune difficulté prioritaire relevée. La visio pourra consolider les stratégies efficaces.</p>}</section><section><h2>Questionnaire d’explicitation préparé</h2><p className="ecf-question-intro">Ces questions servent à comprendre la démarche de l’apprenant, sans le juger ni supposer la cause de ses erreurs.</p><ol><li>Peux-tu me raconter comment tu t’y es pris·e, du début à la fin, pour réaliser l’épreuve ?</li><li>À quel moment t’es-tu senti·e le plus à l’aise ? À quel moment as-tu hésité ?</li>{failed.slice(0,5).map(c=><li key={c.title}>{c.question}</li>)}<li>Qu’est-ce qui pourrait t’aider à réussir plus facilement la prochaine fois ?</li><li>Quelle première action souhaites-tu mettre en place ?</li></ol><div className="ecf-visio"><span>PROCHAINE ÉTAPE</span><strong>Visio avec la formatrice</strong><p>Reprendre les observations, vérifier les hypothèses avec l’apprenant et convenir ensemble du plan d’action.</p></div></section></div><button className="ecf-secondary" onClick={()=>window.print()}>IMPRIMER LE DOSSIER DE REMÉDIATION</button><Link className="ecf-primary link" href="/day4">RETOUR AU DAY 4</Link></div>}
 </section></main>
}
